[package]
name = "mina-signer"
version = "0.1.0"
description = "The mina signer"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
mina-curves = { path = "../curves", version = "0.1.0" }
mina-hasher = { path = "../hasher", version = "0.1.0" }
o1-utils = { path = "../utils", version = "0.1.0" }

ark-ec = { version = "0.3.0", features = [] }
ark-ff = { version = "0.3.0", features = ["asm" ] }

rand = "0.8.0"
blake2 = "0.10.0"
hex = "0.4"
bitvec = "1.0.0"
sha2 = "0.10.0"
bs58 = "0.4.0"
thiserror = "1.0.30"

